### PR TITLE
Add NIST Special Publication 800-208 parameter sets

### PR DESCRIPTION
**Pull request by dcooper16**
This PR adds support for the parameter sets in the draft version of [NIST Special Publication 800-208](https://csrc.nist.gov/publications/detail/sp/800-208/draft). Since [IANA](https://www.iana.org/assignments/xmss-extended-hash-based-signatures/xmss-extended-hash-based-signatures.xhtml) has not yet assigned numeric identifiers for these parameter sets, numeric identifiers randomly chosen from the "Reserved for Private Use" range have been chosen, with the idea that these will be changed once IANA has made assignments.

### CODE REVIEW

**Comment by joostrijneveld** [comment]
I'm somewhat hesitant to set random identifiers in the reference code and then create inconsistency when IANA does assign identifiers.. Is there a practical reason for wanting these identifiers in the reference code before publication of SP 800-208?

**Comment by dcooper16** [comment]
Hi @joostrijneveld,

My interpretation of the IANA considerations section of [RFC 8391](https://www.rfc-editor.org/rfc/rfc8391.html#section-8) was that one of the requirements for having a new entry added to the registry was to have a reference implementation available. If possible, we would like to include the final numeric identifiers for the new parameter sets in final version of SP 800-208. Even if my understanding is correct, though, it is probably enough for the PR to be available even if it hasn't been merged.

I'll update this PR once numeric identifiers for the new parameter sets appear at https://www.iana.org/assignments/xmss-extended-hash-based-signatures/xmss-extended-hash-based-signatures.xhtml. In the meantime, please let me know if you notice any other problems with the PR.

**Comment by dcooper16** [comment]
Hi @joostrijneveld,

The numeric identifiers for the new parameter sets have been posted to https://www.iana.org/assignments/xmss-extended-hash-based-signatures/xmss-extended-hash-based-signatures.xhtml, and I have updated this PR to use the assigned numbers.

**Comment by joostrijneveld** [comment]
Thanks! It's great to have these numbers fixed.

Looks good to me!

**Pull request merged**
